name: lit_eracy
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  flutter_svg: ^2.0.5
  camera: ^0.10.0
  image_picker: ^0.8.6+1
  tflite_flutter: ^0.10.0
  image: ^4.0.15
  logger: ^1.3.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  google_fonts: ^4.0.4
  sqflite: ^2.3.0
  connectivity_plus: ^5.0.2
  path: ^1.8.3
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/