version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=literacy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7
    
volumes:
  postgres_data: